name: location_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^10.4.3
  path_provider: ^2.0.15
  flutter_riverpod: ^2.3.6
  dio: ^5.3.0
  provider: ^6.0.5
  supabase_flutter: ^1.10.11
  url_launcher: ^6.1.12
  receive_intent: ^0.2.4
  uni_links: ^0.5.1
  pinput: ^3.0.0
  cached_network_image: ^3.2.3
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  flutter_map_tile_caching: ^9.0.0-dev.3
  geolocator: ^9.0.2
  easy_image_viewer: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Futura BT
      fonts:
        - asset: assets/fonts/futura-medium-bt.ttf
          weight: 500
        - asset: assets/fonts/futura-heavy-bt.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
